version: "3"

services:

  api:
    build: ./backend/.
    # command: bash -c "uvicorn app:app --host 0.0.0.0 --port 5000 --reload"
    command: bash -c "python3 backend/app.py --host 0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - local-net


  db:
    hostname: db
    container_name: db
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql 
    networks:
      - local-net


  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - db
      environment:
        ADMINER_DEFAULT_SERVER: db
      networks:
        - local-net

volumes:
  mysql-db:
    driver: local

networks:
  local-net:
    driver: bridge