version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

      

