version: "3"

services:

  api:
    build: ./backend/.
    command: python3 backend/app.py
    volumes:
      - .:/code
    container_name: api
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - local-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend:/app
    networks:
      - local-net   

  db:
    hostname: db
    container_name: db
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql 
    networks:
      - local-net


  # adminer:
  #     image: adminer:latest
  #     restart: unless-stopped
  #     ports:
  #       - 8000:8080
  #     depends_on:
  #       - db
  #     environment:
  #       ADMINER_DEFAULT_SERVER: db
  #     networks:
  #       - local-net

volumes:
  mysql-db:

networks:
  local-net:
