"""change the foreign key of order id to UUID

Revision ID: 17bbad8dff14
Revises: 06f800bbe7e0
Create Date: 2021-12-06 19:00:41.870139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bbad8dff14'
down_revision = '06f800bbe7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
