"""remove order tables

Revision ID: 341212fcfaec
Revises: 9be632f55c59
Create Date: 2021-12-06 19:09:31.944561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341212fcfaec'
down_revision = '9be632f55c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_id', table_name='order')
    op.drop_table('order')
    op.drop_index('ix_order_item_id', table_name='order_item')
    op.drop_table('order_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_item_id', 'order_item', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(), nullable=False),
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.INTEGER(), nullable=True),
    sa.Column('modified_time', sa.INTEGER(), nullable=True),
    sa.Column('items_price', sa.INTEGER(), nullable=False),
    sa.Column('shipping_price', sa.FLOAT(), nullable=False),
    sa.Column('tax_price', sa.FLOAT(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_id', 'order', ['id'], unique=False)
    # ### end Alembic commands ###
