"""change order id to UUID

Revision ID: 06f800bbe7e0
Revises: c257c26ac873
Create Date: 2021-12-06 18:56:42.603201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f800bbe7e0'
down_revision = 'c257c26ac873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
