version: '3.12'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ntue
      POSTGRES_USER: ntue
      POSTGRES_PASSWORD: ntuedtd
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
