"""order items table add full content

Revision ID: 7844566c8a5a
Revises: e2a0e757799a
Create Date: 2021-12-06 20:24:26.800695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7844566c8a5a'
down_revision = 'e2a0e757799a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('order_item', sa.Column('category', sa.String(), nullable=True))
    op.add_column('order_item', sa.Column('name', sa.String(), nullable=True))
    op.add_column('order_item', sa.Column('image', sa.String(), nullable=True))
    op.add_column('order_item', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('order_item', sa.Column('countInStock', sa.Integer(), nullable=True))
    op.drop_column('order_item', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('quantity', sa.INTEGER(), nullable=False))
    op.drop_column('order_item', 'countInStock')
    op.drop_column('order_item', 'price')
    op.drop_column('order_item', 'image')
    op.drop_column('order_item', 'name')
    op.drop_column('order_item', 'category')
    op.drop_column('order_item', 'qty')
    # ### end Alembic commands ###
