"""add nullable=True to UUID

Revision ID: 9be632f55c59
Revises: 17bbad8dff14
Create Date: 2021-12-06 19:05:16.382179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be632f55c59'
down_revision = '17bbad8dff14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
